ALTER TYPE "public"."EventType" ADD VALUE 'RIDER_CREATED' BEFORE 'RIDER_DELETED';--> statement-breakpoint
ALTER TYPE "public"."EventType" ADD VALUE 'RIDER_UPDATED' BEFORE 'RIDER_DELETED';--> statement-breakpoint
ALTER TYPE "public"."EventType" ADD VALUE 'RIDER_STATUS_CHANGED' BEFORE 'RIDER_DELETED';--> statement-breakpoint
ALTER TYPE "public"."EventType" ADD VALUE 'DISPATCHER_CREATED' BEFORE 'DISPATCHER_DELETED';--> statement-breakpoint
ALTER TYPE "public"."EventType" ADD VALUE 'DISPATCHER_UPDATED' BEFORE 'DISPATCHER_DELETED';--> statement-breakpoint
ALTER TYPE "public"."EventType" ADD VALUE 'DISPATCHER_STATUS_CHANGED' BEFORE 'DISPATCHER_DELETED';