-- Add missing EventType enum values
ALTER TYPE "public"."EventType" ADD VALUE IF NOT EXISTS 'RIDER_DOCUMENTS_VERIFIED';
ALTER TYPE "public"."EventType" ADD VALUE IF NOT EXISTS 'RIDER_DOCUMENTS_REJECTED';
ALTER TYPE "public"."EventType" ADD VALUE IF NOT EXISTS 'LOGIN';
ALTER TYPE "public"."EventType" ADD VALUE IF NOT EXISTS 'LOGOUT';
ALTER TYPE "public"."EventType" ADD VALUE IF NOT EXISTS 'PROFILE_UPDATE';
